suhas-sunder/EmojiKitchenGame-Open-Source

- vite.config.ts
-Update port in vite config to determine a port for development and production.
> feat: update port

- app/client/components/layout/FirstEmojiWindow.tsx
- app/root.tsx
- server.js
-Make minor changes to cleanup code and increase load times including disabling initial load animation.
> fix: load times

- server.js
-Add middleware to log incoming requests to troubleshoot errors.
> refactor: server.js

- app/root.tsx
Improved error handling and caching.
> fix: Handle gzipped JSON data fetching

- server.js
Fixes TypeError by correcting middleware functions. Ensures proper use of 'next()' in logging and error handling middleware.
> fix: correct Express middleware setup

- app/root.tsx
Add logic to handle fetching and decompressing gzip-compressed JSON files.
> fix: fetch gzip

- app/root.tsx
-Fix issue with fetching filename.json by adding correct route filename.json.gz.
> fix: api route

- app/root.tsx
- Converted ArrayBuffer to Uint8Array for proper gzip decompression with pako.
- Added detailed logging for response headers, status, and decompressed data to aid debugging.
- Improved error handling and logging to better capture and diagnose issues with JSON parsing.
> fix: correctly handle and decompress gzip data

- app/root.tsx
- Adjusted gzip detection and decompression logic.
- Removed unnecessary logging and streamlined error handling.
- Ensured proper handling of both compressed and uncompressed data.
> fix: gzip decompression issues

- app/root.tsx
- package-lock.json
- package.json
-Add Gzip compression back to fetched files in root for improved performance.
> refactor: gzip compression

- app/client/components/layout/ThirdEmojiWindow.tsx
- app/routes/_index.tsx
- public/ads.txt
- public/robots.txt
-Add robots.txt -Add ads.txt -Fix issue where second emoji was copying undefined to clipboard instead of the actual emoji, which wasn't being added to state sometimes.
> fix: add dependencies & fix copying issue

- app/client/components/layout/ComboImage.tsx
- package-lock.json
- package.json
- Refactor image copy logic to use native clipboard API instead of external library
- Implement state management for copy success message
- Ensure compatibility with different environments
> refactor: improve image copy functionality

- app/client/components/layout/ComboImage.tsx
Enhanced the copyImgToClipboard function to ensure compatibility across browsers. Added proper handling of image Blob and state management for the 'Copied!' message. This should address issues with copying images to clipboard on mobile and Safari.
> fix: improve image copy functionality

- app/client/components/layout/ComboImage.tsx
Refactored copyImgToClipboard function to utilize canvas for drawing images before copying to clipboard. Improved Blob handling and state management for the 'Copied!' message. This update aims to resolve issues with copying images to clipboard on mobile and Safari browsers.
> fix: refactor image copy functionality using canvas

- app/client/components/layout/ComboImage.tsx
- package-lock.json
- package.json
Enhanced the copyImgToClipboard function with detailed console logging for better debugging. Added logs for image fetching, canvas operations, and clipboard actions to help identify issues in Safari and other browsers. This should assist in troubleshooting problems related to copying images to clipboard.
> debug: add console logs for image copy functionality

- app/client/components/layout/ComboImage.tsx
Refactored copyImgToClipboard function to handle image-to-blob conversion more robustly. Added additional error handling and logging to better diagnose issues with image copying on mobile devices. Incorporated an alternative approach using data URLs to enhance compatibility across different browsers and devices.
> fix: improve image copy functionality for mobile devices

- app/client/components/layout/ComboImage.tsx
Improved the copyImgToClipboard function with enhanced error handling and logging. Added checks for network response, blob creation, and Clipboard API support. This should help in diagnosing and resolving issues related to copying images to the clipboard.
> fix: enhance image copy functionality and error handling

- app/client/components/layout/ComboImage.tsx
Enhanced the copyImgToClipboard function with better error handling and logging. Added checks for network responses, blob creation, and Clipboard API support. Implemented a fallback mechanism to handle errors by copying a default image to the clipboard if the primary image copy fails.
> fix: improve clipboard image copying and error handling

- app/client/components/layout/ComboImage.tsx
Updated the copyImgToClipboard function to handle image copying using a direct promise approach for the Clipboard API. Removed the fallback mechanism and complex logic involving canvas creation. This change aims to streamline clipboard functionality and improve error handling.
> fix: refactor image copying to clipboard with direct promise approach

- app/client/components/layout/ComboImage.tsx
Refactored the copyImgToClipboard function to use a direct promise approach with the Clipboard API. Removed fallback logic and complex canvas handling. This update addresses clipboard permission issues and simplifies error handling to ensure better functionality.
> fix: adjust image copying to handle permission issues

- app/client/components/layout/ComboImage.tsx
-Add a placeholder image to copy to clipboard to see if it reloves issues with mobile browsers.
> debug: placeholder img

- app/client/components/layout/ComboImage.tsx
-Refactor clipboard copying logic to be directly triggered by user click to comply with browser security restrictions.
> fix: ensure clipboard operation triggers from user interaction

- app/client/components/layout/ComboImage.tsx
Implemented caching of image blobs in state to reduce API calls. Images are fetched and stored when emojis change, improving clipboard operations efficiency and reducing network requests.
> feat: manage image caching for clipboard operations

- app/client/components/layout/ComboImage.tsx
- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/layout/ThirdEmojiWindow.tsx
- app/routes/_index.tsx
-Refactor styling for the interactive window at the bottom that manages the emoji display.
> styling: bottom display

- app/client/components/layout/ComboImage.tsx
-Add logic to handle edge case for a combo emoji url that isn't being displayed.
> fix: third emoji

- app/client/components/layout/ComboImage.tsx
- app/routes/_index.tsx
-Hide display menu by default and add a button that allows users to toggle the menu open.
> feat: hide menu

- app/client/components/ui/CopyPasteTextbox.tsx
- app/routes/copy-and-paste.text-faces.tsx
-Fix issue with input text being trimmed unnecessairly. -Add styling to prevent long text faces from separating due to line breaks.
> fix: text faces

- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/layout/ThirdEmojiWindow.tsx
- app/client/components/ui/CopyPasteTextbox.tsx
- app/routes/_index.tsx
- app/routes/copy-and-paste.text-faces.tsx
- app/routes/emoji-combos.tsx
- package-lock.json
- package.json
-Memoize content being loaded on home page where needed to minimize re-rendering.
> refactor: memoize home page

- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/layout/ThirdEmojiWindow.tsx
- app/client/components/ui/CopyPasteTextbox.tsx
- app/routes/copy-and-paste.text-faces.tsx
- app/routes/emoji-combos.tsx
-Reduce dom size on home page and emoji combo page by limiting the mapped objects being displayed on first render.
> fix: dom size

- app/client/components/hooks/useResponsive.tsx
- app/client/components/hooks/useWindowWidth.tsx
- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/routes/_index.tsx
-Move responsive optimization code into it's own hook.
Add hook that checks window width to determine how many elements should be displayed on screen.
> refactor: dom optimization

- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/routes/_index.tsx
-Add fade animation to all relevant components on home page.
> styling: fade anim

- app/client/components/layout/ComboImage.tsx
- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/ui/SearchBar.tsx
- app/routes/copy-and-paste.emoji-copy-and-paste.tsx
- app/routes/emoji-combos.tsx
-Refactor useEffect that handles combo calculations to include all combinations that were missed and also to make it more performant.
> refactor: combo url

- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/ui/SearchBar.tsx
- app/routes/emoji-combos.tsx
-Refactor searchbar component to allow for custom styling on the search emoji.
-Refactor custom styling for search emoji on searchbar for all related coponents so that the emoji is displayed in the correct position.
> styling: search emoji

- app/routes/_index.tsx
Implemented prefetching of emoji images based on 'firstEmoji' and 'secondEmoji' updates. Added caching for image URLs and blobs to avoid redundant fetches. Updated 'handleCopyClick' to use cached images and blobs for clipboard operations.
> Add image prefetching and caching for emoji component

- app/routes/_index.tsx
Refactored code to ensure emojis are properly normalized and prefetched. Added checks to prevent redundant fetching. Cleaned up console logs.
> Fix emoji image fetching and copying

- app/client/components/layout/SecondEmojiWindow.tsx
- app/root.tsx
- app/routes/_index.tsx
- package-lock.json
- package.json
- Removed unnecessary console logs.
- Added isImageReady state to track image readiness for copying.
- Optimized prefetchImages function to avoid redundant API calls by checking localforage.
- Ensured images are not prefetched multiple times to reduce API load.
> Refactor EmojiHandler component to optimize image prefetching and copying

- app/client/components/layout/FirstEmojiWindow.tsx
- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/navigation/NavBar.tsx
- app/client/components/navigation/styles/NavBar.module.css
- app/routes/$.tsx
- app/routes/cookies-policy.tsx
- app/routes/copy-and-paste.text-faces.tsx
- app/routes/copy-and-paste.tsx
- app/routes/emoji-combos.$emoji.tsx
- app/routes/privacy-policy.tsx
- app/routes/sitemap.tsx
- app/routes/terms-of-service.tsx
-Add minor optimizations to all pages such as adding/improving meta tags, making small style changes, etc.
> refactor: minor polish

- app/routes/_index.tsx
- app/routes/emoji-combos.$emoji.tsx
-Add logic to format unicode in url to account for strangely forammted urls with dsash (-) instead of underscore (_).
> fix: prefetch & copy paste url

- app/root.tsx
-Add delay to GA only on the first render. After that load data instantly.
> fix: ReactGA load delay

- app/client/components/layout/SecondEmojiWindow.tsx
- app/client/components/ui/CopyPasteTextbox.tsx
- app/routes/_index.tsx
- app/routes/copy-and-paste.text-faces.tsx
- app/routes/copy-and-paste.tsx
- app/routes/emoji-combos.$emoji.tsx
- app/routes/emoji-combos.tsx
- app/routes/sitemap.tsx
-Refactor textarea so that mixed media content can be pasted alongside text.
-Add a button that copies all text content.
-Add a button that clears all text in the textarea.
-Add logic to simulate placeholder text over custom textarea.
> refactor: textarea

- app/client/components/layout/SecondEmojiWindow.tsx
- app/routes/_index.tsx
-Fix issue with second emoji not being displayed or copied from preview window on home page due to an edge case not covering a unique set of unicodes.
> fix: seond emoji display

- app/client/components/ui/CopyPasteTextbox.tsx
-Refactor copy paste logic to make sure users can press and hold paste to copy paste multiple items simultaneously and enable touch events on textbox by making a minor change to styling.
> fix: textarea

- app/client/components/ui/CopyPasteTextbox.tsx
-Add button and functionality to upload images to textarea.
-Add resizing options to allow users to control the size of the textare by cliking on preset size options.
> feat: textbox resizing & photo uploads

- app/routes/copy-and-paste.emoji-copy-and-paste.tsx
- app/routes/copy-and-paste.text-faces.tsx
-Refactor styling for buttons so that when they scale up on hover, the overflow isn't hidden by the parent element.
> styling: buttons

- app/entry.client.tsx
- app/root.tsx
- app/routes/$wildcard.tsx
-Add additional error handeling to action method to account for bots making unwanted request to server, which leads to cluttered logs & unnecessary resource use.
> refactor: wildcard & root

- app/entry.client.tsx
-Delay PostHog init by 5 seconds to ensure it doesn't block rendering.
> refactor: PostHog init

- app/client/components/navigation/__tests__/NavBar.test.tsx
Created describe blocks grouping test specifics for render, initialization, user events
> Navbar updates1

- app/client/components/utils/other/Icon.tsx
- app/client/components/utils/other/__tests__/Icon.test.tsx
- package-lock.json
Tested Icon component:
- rendering of title
- rendering of customStyle
> Test: icon component
